### ISSUE TITLE
Documentation Error - Permissions

### ISSUE THREAD

**Issue by philcockfield** [radixdlt/radixdlt-js-lite#1]
On the [Get Started](https://github.com/radixdlt/radixdlt-js-lite/wiki/Basics#get-started) it lists the permissions as:

    const permissions = [
      'address',
      'balance',
      'send_transaction',
      'send_message',
      'send_application_message',
      'transactions',
      'messages',
      'application_messages'
    ];

It has `send_message` and `send_transaction` singular.  I get a permission error when using this in it's singular form, however the pluralised form works:

    const permissions = [
      'send_transactions',
      'send_messages',
    ];

Possibly the docs have not been updated with new code?

----
Thanks - beautiful API guys!

**Comment by murraco** [comment]
Thanks @philcockfield, good catch!
